export const initialState = {
  
  user: {
    state:'',
    authenticated: false,
  },

  posts: {
    data: [
      {
        _id: '5e887e262647b0e3ccf679ba',
        author: 'Jimenez Mercer',
        title: 'Sint enim proident sint.',
        description: 'Occaecat aliquip consequat proident laborum.',
        imgSrc: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png',
        date_publ: '2020-03-09',
        email: 'jimenezmercer@vertide.com',
        phone: '+48 956545357',
        location: 'Saddlebrooke',
      },
      {
        _id: '5e887e26f05e0a6316a0f993',
        author: 'Rhoda Lamb',
        title: 'Eu non ea anim.',
        description: 'Nulla minim eu nostrud tempor ipsum veniam ex sit. ',
        imgSrc: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png',
        date_publ: '2020-03-06',
        email: 'rhodalamb@vertide.com',
        phone: '+48 888494239',
        location: 'Deltaville',
      },
      {
        _id: '5e887e266eb1c41d879f3d4d',
        author: 'Shelton Dudley',
        title: 'Eiusmod ex sunt.',
        description:
          'Cupidatat nulla ipsum reprehenderit proident consequat ipsum ipsum excepteur. ',
        imgSrc: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png',
        date_publ: '2020-03-30',
        email: 'sheltondudley@vertide.com',
        phone: '+48 973470300',
        location: 'Maplewood',
      },
      {
        _id: '5e887e268c508a39671e2a7d',
        author: 'Rasmussen Chambers',
        title: 'Amet qui aute aliquip.',
        description:
          'Do quis cupidatat consequat ad officia eiusmod ipsum adipisicing officia officia cupidatat voluptate deserunt aliquip.',
        imgSrc: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/005.png',
        date_publ: '2020-03-23',
        email: 'rasmussenchambers@vertide.com',
        phone: '+48 830587363',
        location: 'Onton',
      },
      {
        _id: '5e887e26dfb3fefd6784a1f5',
        author: 'Gayle Hardy',
        title: 'Exercitation mollit.',
        description:
          'Enim proident voluptate officia culpa culpa qui do deserunt quis et laborum.',
        imgSrc: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png',
        date_publ: '2020-03-31',
        email: 'gaylehardy@vertide.com',
        phone: '+48 820429282',
        location: 'Longbranch',
      },
      {
        _id: '5e887e269afd958b5f8c5676',
        author: 'Rowe Ellison',
        title: 'Laboris sint Lorem est.',
        description: 'Proident velit proident ipsum dolor in qui ex minim do.',
        imgSrc: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png',
        email: 'roweellison@vertide.com',
        phone: '+48 811526266',
        location: 'Bellfountain',
      },
      {
        _id: '5e887e26dbefc2a9782306cb',
        author: 'Ola Nieves',
        title: 'Aliqua commodo.',
        description:
          'Nostrud excepteur ullamco ipsum officia quis laboris id ullamco excepteur sit ex.',
        imgSrc: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/008.png',
        date_publ: '2020-03-06',
        email: 'olanieves@vertide.com',
        phone: '+48 945441307',
        location: 'Bradenville',
      },
      {
        _id: '5e887e264bdc14c12e6dcb97',
        author: 'Lula Barber',
        title: 'Sint consectetur exercitation.',
        description: 'Consectetur in nulla tempor non consectetur.',
        imgSrc: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/009.png',
        date_publ: '2020-03-11',
        email: 'lulabarber@vertide.com',
        phone: '+48 919443216',
        location: 'Rosedale',
      },
      {
        _id: '5e887e268f324ba69f44aea6',
        author: 'Suarez Harrell',
        title: 'Eiusmod esse ex amet culpa enim.',
        description:
          'Sit nulla consequat quis sunt est ipsum adipisicing fugiat fugiat esse ex.',
        imgSrc: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/010.png',
        date_publ: '2020-03-15',
        email: 'suarezharrell@vertide.com',
        phone: '+48 878452233',
        location: 'Cascades',
      },
      {
        _id: '5e887e262d7bbf0b6d09c0a5',
        author: 'Liza Beard',
        title: 'Consequat voluptate minim exercitation.',
        description:
          'Velit cupidatat amet proident laborum duis pariatur eu et anim culpa veniam fugiat et esse.',
        imgSrc: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/011.png',
        date_publ: '2020-03-25',
        email: 'lizabeard@vertide.com',
        phone: '+48 804514364',
        location: 'Oberlin',
      },
      {
        _id: '5e887e26be403f337e0966a1',
        author: 'Lesley Chan',
        title: 'Amet eiusmod irure.',
        description: 'Exercitation et exercitation elit aliquip.',
        imgSrc: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/012.png',
        date_publ: '2020-03-02',
        email: 'lesleychan@vertide.com',
        phone: '+48 939503327',
        location: 'Whitehaven',
      },
      {
        _id: '5e887e26b3c3edc41b4e40fc',
        author: 'Wise Mclaughlin',
        title: 'Nostrud exercitation est ore.',
        description:
          'Esse amet ullamco dolore nisi Lorem ut esse incididunt elit nostrud ex incididunt.',
        imgSrc: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png',
        date_publ: '2020-03-18',
        email: 'wisemclaughlin@vertide.com',
        phone: '+48 948491395',
        location: 'Elizaville',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
};
